### ISSUE TITLE
找語音生成API

### ISSUE THREAD

**Issue by Tammy0324** [Tammy0324/Speech#1]

**Comment by chouai925** [comment]
https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/#overview

**Comment by chouai925** [comment]
https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/

**Comment by Tammy0324** [comment]
Azure提供免費試用12個月
目前以此套件使用Python進行實作
