### ISSUE TITLE
模擬使用者介面

### ISSUE THREAD

**Issue by Tammy0324** [Tammy0324/Speech#4]
繪製手稿

**Comment by chouai925** [comment]
開機畫面
![48145B3E-FB12-49AC-B5B1-E8D7B0458E91](https://user-images.githubusercontent.com/71805828/149648781-f74c3284-6fdf-4b10-b4ee-6427d502b317.jpeg)

**Comment by chouai925** [comment]
![E1EAC7EE-8459-4A56-9C8C-CDD45C0BB8D4](https://user-images.githubusercontent.com/71805828/149648802-909ee720-7ea6-4c58-baf0-51f8f863979d.jpeg)
